-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 18:00:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vehicle_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vehicle_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vehicle_db` DEFAULT CHARACTER SET utf8 ;
USE `vehicle_db` ;

-- -----------------------------------------------------
-- Table `vehicle_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicle_db`.`role` (
  `ro_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ro_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicle_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicle_db`.`user` (
  `us_id` BIGINT NOT NULL AUTO_INCREMENT,
  `us_first_name` VARCHAR(45) NULL DEFAULT NULL,
  `us_last_name` VARCHAR(45) NULL DEFAULT NULL,
  `us_age` INT NULL DEFAULT NULL,
  `us_gender` VARCHAR(45) NULL DEFAULT NULL,
  `us_contact_number` BIGINT(20) NULL DEFAULT NULL,
  `us_email_id` VARCHAR(50) NULL DEFAULT NULL,
  `us_password` VARCHAR(255) NOT NULL,
  `us_user_name` VARCHAR(45) NOT NULL,
  `us_branch` VARCHAR(45) NULL DEFAULT NULL,
  `us_active` boolean NULL DEFAULT 0,
  PRIMARY KEY (`us_id`),
  UNIQUE INDEX `us_user_name_UNIQUE` (`us_user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicle_db`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicle_db`.`user_role` (
  `ur_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ur_ro_id` BIGINT NOT NULL,
  `ur_us_id` BIGINT NOT NULL,
  INDEX `fk_role_has_user_user1_idx` (`ur_us_id` ASC),
  INDEX `fk_role_has_user_role_idx` (`ur_ro_id` ASC),
  PRIMARY KEY (`ur_id`),
  CONSTRAINT `ur_ro_fk_idx`
    FOREIGN KEY (`ur_ro_id`)
    REFERENCES `vehicle_db`.`role` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ur_us_fk_idx`
    FOREIGN KEY (`ur_us_id`)
    REFERENCES `vehicle_db`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicle_db`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicle_db`.`vehicle` (
  `ve_id` BIGINT NOT NULL AUTO_INCREMENT,
  `ve_name` VARCHAR(45) NOT NULL,
  `ve_model` VARCHAR(45) NOT NULL,
  `ve_number` VARCHAR(45) NOT NULL,
  `ve_year_of_manufacturing` DATE NOT NULL,
  `ve_insurance_renewal_date` DATE NOT NULL,
  `ve_last_service_date` DATE NOT NULL,
  `ve_next_service_date` DATE NOT NULL,
  `ve_seater` INT NOT NULL,
  `ve_type_of_vehicle` VARCHAR(45) NOT NULL,
  `ve_image_url` VARCHAR(255) NOT NULL,
  `ve_mileage` DOUBLE NOT NULL,
  `ve_rent` DOUBLE NOT NULL,
  PRIMARY KEY (`ve_id`))
ENGINE = INNODB;
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (1,'Renault','Duster','TN 02 CH 1453','2016-01-01','2020-12-26','2019-07-04','2020-07-04',5,'Car','https://stimg.cardekho.com/images/carexteriorimages/930x620/Renault/Renault-Duster/7014/1562581388944/front-left-side-47.jpg',19.87,600);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (2,'Hyundai','Grand i10','KA 06 FG 9865','2016-04-05','2022-11-09','2019-08-09','2020-08-09',5,'Car','https://images.unsplash.com/photo-1575090536203-2a6193126514?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',18.9,555);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (3,'Honda','Navi','TN 12 AA 4578','2015-09-08','2019-01-31','2019-07-07','2020-07-02',2,'Bike','https://images.unsplash.com/photo-1527905890126-e4d915153e25?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',18.5,400);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (4,'Volkswagen','Polo','PY 06 BC 2345','2018-10-12','2020-01-02','2019-04-03','2020-04-03',5,'Car','https://stimg.cardekho.com/images/carexteriorimages/630x420/Volkswagen/Volkswagen-Polo/7143/1567599623608/front-left-side-47.jpg?tr=w-456,e-sharpen',21.49,600);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (5,'Jeep','Compass Trailhawk','TN 02 CH 1453','2012-12-02','2019-12-11','2019-11-05','2019-12-20',5,'Car','https://stimg.cardekho.com/images/carexteriorimages/630x420/Jeep/Jeep-Trailhawk/6974/1561461281768/front-left-side-47.jpg?tr=w-456,e-sharpen',14,650);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (6,'Ford','Mustang','AP 11 BH 6454','1998-11-05','2020-01-14','2019-11-01','2019-12-28',4,'Car','https://stimg.cardekho.com/images/carexteriorimages/630x420/Ford/Mustang/1102/1569565000696/front-left-side-47.jpg?tr=w-456,e-sharpen',13,850);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (7,'Soppana Sundari Car','Duster','TN 02 CH 1411','1990-01-01','2020-12-26','2019-07-06','2020-07-06',4,'Car','https://images.unsplash.com/photo-1571608424964-97768e1726ce?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',8.9,1500);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (8,'Triumph','Bonneville ','TN 12 AA 1444','2010-08-09','2015-08-07','2014-08-09','2020-07-05',2,'Bike','https://cdn2.cycletrader.com/v1/media/5c01dec10b08ae299c0f09f4.jpg?width=1024&height=768&quality=70',21.9,500);
INSERT INTO `vehicle` (`ve_id`,`ve_name`,`ve_model`,`ve_number`,`ve_year_of_manufacturing`,`ve_insurance_renewal_date`,`ve_last_service_date`,`ve_next_service_date`,`ve_seater`,`ve_type_of_vehicle`,`ve_image_url`,`ve_mileage`,`ve_rent`) VALUES (9,'Bajaj','Maxima','TN 12 AA 9999','0007-01-01','2017-01-30','2019-07-04','2020-11-04',3,'Auto','https://images.unsplash.com/photo-1527488224604-c972833080f0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60',15.2,150);


-- -----------------------------------------------------
-- Table `vehicle_db`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicle_db`.`booking` (
  `bo_id` BIGINT NOT NULL AUTO_INCREMENT,
  `bo_start_date` DATETIME NOT NULL,
  `bo_end_date` DATETIME NOT NULL,
  `bo_status` boolean NOT NULL,
  `bo_total` DOUBLE NOT NULL,
  `bo_ve_id` BIGINT NOT NULL,
  `bo_us_id` BIGINT NOT NULL,
  INDEX `bo_ve_id` (`bo_ve_id` ASC),
  INDEX `bo_us_id` (`bo_us_id` ASC),
  PRIMARY KEY (`bo_id`),
  CONSTRAINT `bo_ve_id`
    FOREIGN KEY (`bo_ve_id`)
    REFERENCES `vehicle_db`.`vehicle` (`ve_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bo_us_id`
    FOREIGN KEY (`bo_us_id`)
    REFERENCES `vehicle_db`.`user` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicle_db`.`payment_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicle_db`.`payment_account` (
    `pa_id` BIGINT NOT NULL AUTO_INCREMENT,
    `pa_card_number` BIGINT NOT NULL,
    `pa_cvv_number` BIGINT NOT NULL,
    `pa_card_expiry_date` DATE NOT NULL,
    `pa_bank` VARCHAR(45) NOT NULL,
    `pa_card_holder_name` VARCHAR(45) NOT NULL,
    `pa_account_balance` DOUBLE NOT NULL,
    PRIMARY KEY (`pa_id`)
)  ENGINE=INNODB;
-- -----------------------------------------------------
-- Table `vehicle_db`.`payment_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicle_db`.`transactions`(
  `tr_id` BIGINT NOT NULL AUTO_INCREMENT,
  `tr_bo_id` BIGINT NOT NULL,
  `tr_pa_id` BIGINT NOT NULL,
  PRIMARY KEY (`tr_id`),
  CONSTRAINT `fk_transactions_booking`
    FOREIGN KEY (`tr_bo_id`)
    REFERENCES `vehicle_db`.`booking` (`bo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_account`
    FOREIGN KEY (`tr_pa_id`)
REFERENCES `vehicle_db`.`payment_account` (`pa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;  

INSERT INTO `user`(us_user_name,us_password,us_branch,us_active) VALUES ('admin','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK','CHENNAI',1),('user','$2a$10$R/lZJuT9skteNmAku9Y7aeutxbOKstD5xE5bHOf74M2PHZipyt3yK','',1);

INSERT INTO `role` (ro_name) VALUES ('ADMIN'),('USER');

INSERT INTO `user_role` (ur_ro_id,ur_us_id) VALUES (1,1),(2,2);

INSERT INTO payment_account (pa_card_number, pa_cvv_number,pa_card_expiry_date,pa_bank,pa_card_holder_name,pa_account_balance)
VALUES(1234567890123456,123,'12/12/2020','SBI','Emmanuel',90000);
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
